### ISSUE TITLE
snap installed croc can't access file in home directory - permission denied

### ISSUE THREAD

**Issue by Jakethethird** [schollz/croc#190]
**Describe the bug**
Croc installed on Ubuntu 19.10 via sudo snap install croc or via software centre cannot access files in home directory

**To Reproduce**

```
jake@jts-800:~$ croc send Camera1_2020_01_04.avi 
open /home/jake/Camera1_2020_01_04.avi: permission denied
```

Neither cli nor store provide option to change permissions:
http://www.linuxandubuntu.com/home/snap-application-permissions

```
jake@jts-800:~$ snap interfaces croc
error: no interfaces found
jake@jts-800:~$ snap connect croc:home
error: snap "croc" has no plug named "home"
```

![20200112_SelectionNN](https://user-images.githubusercontent.com/28954472/72221403-518ce500-3552-11ea-84d9-be9e0fe52950.png)

**Version**
croc version v6.4.8-fd20b25
Ubuntu 19.10

**Comment by schollz** [comment]
Thanks. I forgot to add plugs. They are there now, hopefully.

**Comment by Jakethethird** [comment]
Hello, 
Now it runs but I get the following error. Is this OK?

```
jake@jts-800:~/Temp$ croc send test.txt
Sending 'test.txt' (0 B)
Code is: nylon-logo-sandra
On the other computer run

croc nylon-logo-sandra
[error]	2020/01/15 17:58:11 tcp.go:79: Error listening on :9011: listen tcp :9011: listen: operation not permitted
panic: Error listening on :9011: listen tcp :9011: listen: operation not permitted

goroutine 9 [running]:
github.com/schollz/croc/v6/src/croc.(*Client).setupLocalRelay.func1(0xc000001680, 0x897ef9, 0x4)
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:248 +0x157
created by github.com/schollz/croc/v6/src/croc.(*Client).setupLocalRelay
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:241 +0x85
```

I turned off my laptop firewall (gufw)

```
jake@jts-800:~/Temp$ croc send test.txt
Sending 'test.txt' (0 B)
Code is: pepper-chef-magenta
On the other computer run

croc pepper-chef-magenta
[error]	2020/01/15 18:00:39 tcp.go:79: Error listening on :9013: listen tcp :9013: listen: operation not permitted
panic: Error listening on :9013: listen tcp :9013: listen: operation not permitted

goroutine 23 [running]:
github.com/schollz/croc/v6/src/croc.(*Client).setupLocalRelay.func1(0xc0000aa600, 0x897f03, 0x4)
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:248 +0x157
created by github.com/schollz/croc/v6/src/croc.(*Client).setupLocalRelay
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:241 +0x85
jake@jts-800:~/Temp$ 

```

**Comment by schollz** [comment]
Yeah, I realized it needed network access too, it should be [fixed now](https://github.com/schollz/croc/commit/073569f29256cd9e691ca50ac52bf481015adbe6)

**Comment by Jakethethird** [comment]
OK, here is a test file for you to download from my refreshed snap install:

`croc acid-food-finish`

If it works, we can close this issue. I'll leave it open for a short while.

jake

**Comment by schollz** [comment]
@Jakethethird Sorry, I'm not going to download a file from you - just test between two computers you have access to.

**Comment by Jakethethird** [comment]
OK, I confirm it works on the same LAN but can't test it from a remote PC. I'll close the file share.
Thanks.

**Comment by rudluff** [comment]
I still get this in the 8.0.10 version (also installed via snap). Via some testing, croc specifically hates dotfiles, dot-directories, and non-dot-files that live in dot-directories. (Also, the debug flag either isn't working or needs an undisclosed parameter.)

```
~/.config/rclone$ croc rclone.conf 
Did you mean to send 'rclone.conf'? (y/n) y
open /home/user/.config/rclone/rclone.conf: permission denied
~/.config/rclone$ ls -al
total 20
drwxrwxr-x  2 user user  4096 May  9 13:26 .
drwxr-xr-x 85 user user  4096 May  9 12:28 ..
-rw-rw-r--  1 user user 10605 May  9 13:20 rclone.conf
~/.config/rclone$ croc rclone.conf --debug
Did you mean to send 'rclone.conf'? (y/n) y
stat --debug: no such file or directory
~/.config/rclone$ croc help debug
No help topic for 'debug'
~/.config/rclone$ cd
~$ touch .ligma
~$ croc .ligma
open /home/user/.ligma: permission denied
```

**Comment by schollz** [comment]
Ugh, its a snap issue. I added the `personal-files` plug, but I need to wait for them to approve:

```
Pushing 'croc_8.0.11_linux_386.snap.xdelta3' [===========================] 100%
Processing...|                                                                 
Will need manual review...
The Store automatic review failed.
A human will soon review your snap, but if you can't wait please write in the snapcraft forum asking for the manual review explicitly.
If you need to disable confinement, please consider using devmode, but note that devmode revision will only be allowed to be released in edge and beta channels.
Please check the errors and some hints below:
  - human review required due to 'allow-installation' constraint (bool)
```

**Comment by schollz** [comment]
Snap form: https://forum.snapcraft.io/t/croc-needs-permission-for-dotfiles-in-home/17424

Revision (waiting for manual review): https://dashboard.snapcraft.io/snaps/croc/revisions/96/

**Comment by schollz** [comment]
@rudluff Okay it turns out, as of now, there is really no way to let the snap installed version of croc access dot files. Each way of doing it presents more insurmountable problems.

Way 1: I could enable `personal-files` in the snap, but I'd have to specify each file individually and there is no way for me to know which files you'll send lol.

Way 2: I could do `classic` confinement but it won't work on Ubuntu core then and it may see the wrong file system.

Maybe there is another way? I would be open to anything else, otherwise my recommendation is not to use snap.

**Comment by rudluff** [comment]
Damn, that's wild! Glad to know it's sandboxing run amok, I thought it was a base croc trait. I'll just go with the deb.

I worked around it by the stupid method of copying rclone.conf to my home directory, then croc'ing it. Only way I could think of to communicate this to end-users is some kind of an error message like "Croc is not allowed to interact with dotfiles or dotfolders when installed from snap package. Consider making a sanitized filename/path." (of course, depends on if there is even any way to detect it's a snap/dotfile permission issue versus a _normal_ user permissions issue, and if the snap marketplace moderation team [?!] lets you put in a message like that).

**Comment by schollz** [comment]
Since this is a snap issue, I'm going to close this. I'll keep snap around, but keep note that it may not work all the time with croc :(

**Comment by colindaven** [comment]
Croc installed via Ubuntu snap seems to have issues with non-local NFS storage too, even when not used with dotfiles etc as above.

cannot open path of the current working directory: Permission denied
